#!/usr/bin/env bash
# Collects the SHA256 of every release asset and emits prebuilt-manifest.cmake.
#
# Usage:
#   generate_manifest.sh <artifacts-dir> <openssl-version>
#
# A consuming project's cmake/prebuilt/fetch_prebuilt.cmake downloads this file
# first, include()s it, and checks that its triple is present and that the
# archive hash matches.
#
# Why the hashes are not committed to the repo:
#   the build only runs once a tag is pushed, but the hashes only exist after
#   the build (chicken-and-egg). Shipping the manifest as a release asset breaks
#   that cycle.

set -euo pipefail

ARTIFACTS_DIR="${1:?usage: generate_manifest.sh <artifacts-dir> <openssl-version>}"
OSSL_VERSION="${2:?usage: generate_manifest.sh <artifacts-dir> <openssl-version>}"

MANIFEST="${ARTIFACTS_DIR}/prebuilt-manifest.cmake"

triples=()
shas=()

for archive in "${ARTIFACTS_DIR}"/openssl-"${OSSL_VERSION}"-*.tar.gz; do
    [[ -e "$archive" ]] || continue

    name="$(basename "$archive")"
    # openssl-3.6.1-windows-x64-msvc-release.tar.gz -> windows-x64-msvc-release
    triple="${name#openssl-${OSSL_VERSION}-}"
    triple="${triple%.tar.gz}"

    sha="$(sha256sum "$archive" | cut -d' ' -f1)"

    triples+=("$triple")
    shas+=("$sha")
done

if [[ ${#triples[@]} -eq 0 ]]; then
    echo "[manifest] no archives found in ${ARTIFACTS_DIR}" >&2
    exit 1
fi

{
    echo "# Generated by .github/scripts/generate_manifest.sh — do not edit."
    echo "# OpenSSL ${OSSL_VERSION} prebuilt static libraries."
    echo ""
    echo "set(OPENSSL_PREBUILT_VERSION \"${OSSL_VERSION}\")"
    echo ""
    printf 'set(OPENSSL_PREBUILT_TRIPLES\n'
    for t in "${triples[@]}"; do
        printf '    "%s"\n' "$t"
    done
    printf ')\n\n'
    for i in "${!triples[@]}"; do
        printf 'set(OPENSSL_PREBUILT_SHA256_%s "%s")\n' "${triples[$i]}" "${shas[$i]}"
    done
} > "$MANIFEST"

echo "[manifest] generated ${MANIFEST}"
cat "$MANIFEST"
