#!/usr/bin/env bash
# Packages the built OpenSSL static libraries into a distributable tar.gz.
#
# Usage:
#   package.sh --triple <triple> --build-dir <dir> --lib-ext <a|lib>
#
# Output:
#   dist/openssl-<OPENSSL_VERSION>-<triple>.tar.gz
#
# Archive layout:
#   include/openssl/*.h
#   lib/libcrypto.<ext>
#   lib/libssl.<ext>
#   lib/*.pdb              (MSVC Debug only)
#
# include/ has to be merged from two places:
#   external/openssl/include/openssl  - the original public headers
#   <build>/include/openssl           - headers generated by Configure
#                                       (opensslconf.h, configuration.h, ...)
# The generated headers must win, so copy the originals first and the generated
# ones on top.

set -euo pipefail

TRIPLE=""
BUILD_DIR=""
LIB_EXT=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --triple)    TRIPLE="$2";    shift 2 ;;
        --build-dir) BUILD_DIR="$2"; shift 2 ;;
        --lib-ext)   LIB_EXT="$2";   shift 2 ;;
        *) echo "unknown argument: $1" >&2; exit 1 ;;
    esac
done

if [[ -z "$TRIPLE" || -z "$BUILD_DIR" || -z "$LIB_EXT" ]]; then
    echo "usage: package.sh --triple <t> --build-dir <d> --lib-ext <a|lib>" >&2
    exit 1
fi

: "${OPENSSL_VERSION:?OPENSSL_VERSION must be set}"

# OpenSSL builds into a subdirectory of the CMake build dir, not into the build
# dir itself — otherwise the Makefile generators clobber OpenSSL's Makefile.
# Keep this in sync with openssl_BINARY_DIR in CMakeLists.txt.
OSSL_BUILD="${BUILD_DIR}/openssl-build"

SRC_INC="external/openssl/include/openssl"
GEN_INC="${OSSL_BUILD}/include/openssl"
CRYPTO_LIB="${OSSL_BUILD}/libcrypto.${LIB_EXT}"
SSL_LIB="${OSSL_BUILD}/libssl.${LIB_EXT}"

for p in "$SRC_INC" "$GEN_INC" "$CRYPTO_LIB" "$SSL_LIB"; do
    if [[ ! -e "$p" ]]; then
        echo "[package] expected artifact is missing: $p" >&2
        exit 1
    fi
done

PKG="pkg/${TRIPLE}"
rm -rf "$PKG"
mkdir -p "${PKG}/include/openssl" "${PKG}/lib"

# Originals first, generated headers on top
cp -R "${SRC_INC}/." "${PKG}/include/openssl/"
cp -R "${GEN_INC}/." "${PKG}/include/openssl/"

# .h.in templates are useless to consumers (the generated .h already exists)
find "${PKG}/include" -name '*.h.in' -delete

cp "$CRYPTO_LIB" "${PKG}/lib/"
cp "$SSL_LIB"    "${PKG}/lib/"

# MSVC Debug: ship the PDBs so consumers can step into OpenSSL
shopt -s nullglob
for pdb in "${OSSL_BUILD}"/libcrypto.pdb "${OSSL_BUILD}"/libssl.pdb; do
    cp "$pdb" "${PKG}/lib/"
done
shopt -u nullglob

mkdir -p dist
ARCHIVE="openssl-${OPENSSL_VERSION}-${TRIPLE}.tar.gz"
tar -czf "dist/${ARCHIVE}" -C "$PKG" include lib

echo "[package] created dist/${ARCHIVE}"
ls -lh "dist/${ARCHIVE}"
tar -tzf "dist/${ARCHIVE}" | head -20
